# Generated by Django 4.2.6 on 2024-02-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='full_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='service',
            name='img',
            field=models.ImageField(null=True, upload_to='services/'),
        ),
    ]
