# Generated by Django 4.2.6 on 2024-02-25 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='price',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='img',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subplan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
